Update morpheus_quickstart_guide.md
nv-morpheus/Morpheus pull request #127
Opened 2022-05-25 18:26 UTC by bsuryadevara

Minor updates to Quickstart guide

2022-05-26 15:44 UTC, pdmack requested changes

2022-05-26 15:44 UTC, pdmack commented on docs/source/morpheus_quickstart_guide.md
> +Run the following command to pull the Morpheus SDK Client on your instance:
" to pull the Morpheus SDK Client chart on to "

2022-05-26 15:44 UTC, pdmack commented on docs/source/morpheus_quickstart_guide.md
> +**Note**: For reference, the Morpheus SDK Client install pipeline command template is provided. Let's take a closer look at this when running [example workflows](#example-workflows), but for now, let
" let's proceed to the next step."

2022-05-26 15:44 UTC, pdmack commented on docs/source/morpheus_quickstart_guide.md
> +Install the Morpheus SDK client in sleep mode to save sample datasets and models from the container to a shared location that other pods can access. If no `sdk.args` is supplied, the default value `/
"from the chart" not plural

2022-05-27 14:08 UTC, bsuryadevara commented on docs/source/morpheus_quickstart_guide.md
> +Install the Morpheus SDK client in sleep mode to save sample datasets and models from the container to a shared location that other pods can access. If no `sdk.args` is supplied, the default value `/
As suggested, I've updated it. thank you

2022-06-01 17:10 UTC, dagardner-nv approved these changes
LGTM

2022-06-01 17:11 UTC, dagardner-nv commented
@gpucibot merge

2022-06-01 17:11 UTC, merged