Fea sherlock tests
nv-morpheus/Morpheus pull request #1286
Opened 2023-10-17 23:29 UTC by cwharris

## Description
Tests the python/cpp coroutine binding code (pycoro) to ensure recursive/nested and parallel python and c++ calls can be interleaved without issue. Also allows `PyTaskToCppAwaitable` to be constructed with a raw python coroutine as opposed to only asyncio tasks.

Closes #1268

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2023-10-18 19:20 UTC, mdemoret-nv requested changes
This is a great start but I would like to see more edge cases. The issue has the following listed: 

- Throwing exceptions from C++
- Throwing exceptions from Python
- Cancelling coroutines from python
- Abnormal shutdown of the loop
- Nested layers of python -> C++ -> python -> C++ coroutines

I only see one of those exercised here

2023-10-19 03:59 UTC, mdemoret-nv commented
@cwharris Can you get the check stage to pass and then we can merge?

2023-10-19 03:59 UTC, mdemoret-nv approved these changes

2023-10-26 20:42 UTC, cwharris commented
Closing in favor of https://github.com/nv-morpheus/MRC/pull/409

2023-10-26 20:42 UTC, closed without merging