Split data dir, moving large files into examples/data
nv-morpheus/Morpheus pull request #130
Opened 2022-05-27 20:11 UTC by dagardner-nv

Brings directory size down to 1.6MB down from 270MB

+ Move large files to `exaples/data` 
+ Migrate existing files in `exaples/data` to git-lfs
+ Add missing `email_with_addresses.jsonlines` needed for phishing detection developer guide
+ Update file paths in docs for data files
+ Update import paths in developer guide

Depends on changes in #62 
Fixes #120

2022-06-02 14:43 UTC, raykallen approved these changes
LGTM

2022-06-03 17:54 UTC, mdemoret-nv requested changes
Everything looks good. I'm not sure what the `with_data_len.json` and `without_data_len.json` files are used for. Can you verify that they arent used anywhere and remove them? Otherwise, looks good.

2022-06-03 21:34 UTC, dagardner-nv commented
Removed unused `with_data_len.json` and `without_data_len.json` files

2022-06-07 00:29 UTC, mdemoret-nv requested changes
Need to revert the pinned Neo version

2022-06-07 00:29 UTC, mdemoret-nv commented on docker/conda/environments/cuda11.4_dev.yml
> +    - neo 22.04.00a*
Can we unpin this? Once PR 107 goes in, this should go back to `22.04.*`

2022-06-07 18:18 UTC, mdemoret-nv approved these changes
Looks good now.

2022-06-07 18:18 UTC, merged