Agents Pipeline README.md
nv-morpheus/Morpheus pull request #1352
Opened 2023-11-08 17:30 UTC by bsuryadevara

## Description

Updated agents pipeline README.md

Closes #1307 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2023-11-08 20:45 UTC, drobison00 requested changes

2023-11-08 20:45 UTC, drobison00 commented on examples/llm/agents/README.md
@bsuryadevara Could you bring the format of this in line a bit more closely with the other 3 README.mds.

See: https://github.com/nv-morpheus/Morpheus/blob/fea-sherlock/examples/llm/vdb_upload/README.md

2023-11-13 17:11 UTC, bsuryadevara commented on examples/llm/agents/README.md
Sure

2023-11-13 19:04 UTC, bsuryadevara commented on examples/llm/agents/README.md
@drobison00 Updated as suggested.

2023-11-13 19:07 UTC, drobison00 approved these changes

2023-11-13 23:23 UTC, bsuryadevara commented
/merge

2023-11-13 23:23 UTC, merged