Draft: stage decorator
nv-morpheus/Morpheus pull request #1364
Opened 2023-11-15 17:31 UTC by dagardner-nv

## Description

Closes 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2023-11-17 21:43 UTC, drobison00 approved these changes

2023-11-25 00:01 UTC, mdemoret-nv requested changes
This is a good start but we need some changes to be forward looking with these decorators. General changes:

1. The classes used by the decorators should be "dumber" and move most of the implementation into the decorator instead of the class. See my comments for more details.
2. Need some tests validating the parameters used at construction time
3. Needs documentation showing how this can be used in the developer guide.

2023-11-27 17:48 UTC, dagardner-nv commented on morpheus/pipeline/stage_decorator.py
> +    return wrapper
We do currently support arguments to the stage decorator, it works as both `@stage` and `@stage()`

2023-11-27 17:51 UTC, dagardner-nv commented
> 3. Needs documentation showing how this can be used in the developer guide.

I do have dev-doc updates, I just did them in a different branch. I can merge it back in here.

2023-11-27 17:53 UTC, dagardner-nv commented on morpheus/pipeline/stage_decorator.py
> +        return functools.partial(stage, needed_columns=needed_columns)
That allows us to support both `@stage` and `@stage()` invocations.

2023-11-27 22:40 UTC, dagardner-nv commented on morpheus/pipeline/stage_decorator.py
> +                 on_data_fn: typing.Callable,
I think we should still allow `config` to be positional as it is specified positional in the documentation & examples for all other stages :
```
    def __init__(self,
                 config: Config,
                 *,
                 on_data_fn: typing.Callable,
```

2023-11-28 00:26 UTC, mdemoret-nv commented on morpheus/pipeline/stage_decorator.py
> +                 on_data_fn: typing.Callable,
Thats fine.

2023-11-29 18:41 UTC, mdemoret-nv approved these changes
Looks good now. Like the changes. This will be super useful in the future.

2023-11-29 22:34 UTC, mdemoret-nv commented
/merge

2023-11-29 22:34 UTC, merged