Improve the HTTP server shutdown logic to respond correctly to Ctrl+C and stop commands
nv-morpheus/Morpheus pull request #1517
Opened 2024-02-13 21:03 UTC by mdemoret-nv

## Description
This PR refactors the C++ HTTP server to allow it to correctly stop processing when a user presses Ctrl+C or `pipeline.stop()` is called.

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2024-02-20 16:39 UTC, dagardner-nv requested changes

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/_lib/src/stages/http_server_source_stage.cpp
> +// }
remove

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/_lib/src/stages/http_server_source_stage.cpp
> +// }
remove

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/_lib/src/utilities/http_server.cpp
> +        auto address_str = MRC_CONCAT_STR("[" << m_stream.socket().local_endpoint().address().to_string() << ":"
If we only need this for debug logging, maybe move this under an `ifdef DEBUG`

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/_lib/src/utilities/http_server.cpp
> +        //            << " threads";
Can you re-enable this log line?

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/_lib/src/utilities/http_server.cpp
> +        // started_semaphore.acquire();
Do we not need this anymore?

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/llm/services/openai_chat_service.py
> +        test()
Is this a temporary test?

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/llm/services/openai_chat_service.py
Call this out in the details as a part of the PR

2024-02-20 16:39 UTC, dagardner-nv commented on morpheus/stages/input/http_server_source_stage.py
> +        while True:
Personally I don't like `break` statements I would instead do:
```
done = False
while not done:
....
    except Closed:
        done = True
```

2024-02-21 20:52 UTC, mdemoret-nv commented on morpheus/utils/http_utils.py
> +    import tenacity
Look into moving similar code from sherlock.

2025-04-04 16:44 UTC, Salonijain27 commented
Closing this PR as it has been open for over a year. If required please reopen it.

2025-04-04 16:44 UTC, closed without merging