[DRAFT] Update `morpheus._lib.messages.MessageMeta.get_data_frame()` to use cuDF deep copy
nv-morpheus/Morpheus pull request #1538
Opened 2024-02-28 19:51 UTC by efajardo-nv

## Description
+ Update `morpheus._lib.messages.MessageMeta.get_data_frame()` to use cuDF deep copy

Closes #1527 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2024-02-28 21:08 UTC, mdemoret-nv requested changes
Good start but lets find all uses of the `get_data_frame()` function and convert them to use `copy_dataframe()` and `get_mutable_dataframe()`

2024-02-28 21:08 UTC, mdemoret-nv commented on morpheus/_lib/src/messages/meta.cpp
> +        copied_df = dfcopy();
```suggestion
        py::gil_scoped_acquire gil;
        
        return py_df.attr("copy")();
```

Double check the uses of the GIL here

2024-02-28 21:08 UTC, mdemoret-nv commented on morpheus/_lib/src/messages/meta.cpp
> +        TableInfo info = self.get_info();
I dont think we want to expose the python object in `TableInfo`. Will re-evaluate after seeing the updates to use `copy_dataframe` and `get_mutable_dataframe()`

2024-02-29 02:59 UTC, efajardo-nv commented on morpheus/_lib/src/messages/meta.cpp
> +        copied_df = dfcopy();
removed acquire gil

2024-03-13 19:43 UTC, mdemoret-nv commented on ci/scripts/common.sh
> +export PYTHON_FILE_REGEX='^(\.\/)?(?!\.|build|external).*\.py$'
Lets revert this to allow flake8 to still run on cython files

2024-03-13 19:43 UTC, mdemoret-nv commented on tests/messages/test_message_meta.py
> +    test_df = dataset["test_dataframe.jsonlines"]
This is a good new test dataframe. Lets try any use it more places where we were using `filter_probs` before to ensure there are no more problems.

2024-06-14 17:35 UTC, mdemoret-nv commented
/ok to test

2024-06-17 23:08 UTC, mdemoret-nv commented
/ok to test

2024-06-18 00:36 UTC, mdemoret-nv approved these changes
All tests now passing. Approved

2024-06-18 00:37 UTC, mdemoret-nv commented
/merge

2024-06-18 00:37 UTC, merged