DOCA 2.6 from public repo
nv-morpheus/Morpheus pull request #1588
Opened 2024-04-03 12:28 UTC by e-ago

## Description
Modified the Dockerfile if DOCA is enabled to install with apt DOCA debian packages from public repo instead of the internal repo

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2024-04-03 17:12 UTC, mdemoret-nv requested changes

2024-04-03 17:12 UTC, mdemoret-nv commented on docker/Dockerfile
> +        #doca-runtime \
Should this be removed?

2024-04-03 17:12 UTC, mdemoret-nv commented on docker/Dockerfile
> +        doca-gpu \
Can we alphabetize this list?

2024-04-03 17:12 UTC, mdemoret-nv commented on docker/Dockerfile
> +        ucx \
Can we move this into the `doca.sh` to be contained with the other DOCA install steps?

2024-04-03 18:14 UTC, e-ago commented
@mdemoret-nv I've applied your comments

2024-04-03 20:04 UTC, mdemoret-nv approved these changes

2024-04-04 13:37 UTC, mdemoret-nv commented
/ok to test

2024-04-04 16:52 UTC, mdemoret-nv commented
/ok to test

2024-04-04 20:06 UTC, mdemoret-nv commented
/ok to test

2024-04-05 02:52 UTC, mdemoret-nv commented
/ok to test

2024-04-05 13:49 UTC, mdemoret-nv approved these changes
Have built the new release and dev container with DOCA support. Release container has been tested by @e-ago. Approved.

2024-04-05 13:49 UTC, mdemoret-nv commented
/ok to test

2024-04-05 15:28 UTC, mdemoret-nv commented
/ok to test

2024-04-05 18:53 UTC, mdemoret-nv commented
/merge

2024-04-05 18:54 UTC, merged