Fixes and unit test updates to OpenAI client
nv-morpheus/Morpheus pull request #1698
Opened 2024-05-13 21:33 UTC by efajardo-nv

## Description
- Update unit tests to handle recently added `api_key` and `base_url` parameters.
- Remove `api_key` and `base_url` from `model_kwargs` to prevent client error.
- Ensure log directory exists for logging FileHandler.
- Docstring update

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2024-05-14 15:21 UTC, mdemoret-nv requested changes

2024-05-14 15:21 UTC, mdemoret-nv commented on tests/llm/services/test_openai_chat_client.py
> +    assert isinstance(client, LLMClient)
This is unnecessary.

2024-05-14 16:48 UTC, efajardo-nv commented on morpheus/llm/services/openai_chat_service.py
> +            be used., by default None
That actually is the current pattern. I had a bad pydantic model config that wasn't allowing the `base_url` to be set. I'll fix the docstring.

2024-05-15 20:45 UTC, mdemoret-nv approved these changes

2024-05-15 20:45 UTC, mdemoret-nv commented on tests/llm/services/test_openai_chat_client.py
> +        assert str(client._client.base_url) == arg_base_url
Lets remove this section and revert back to what it was.

2024-05-15 20:45 UTC, mdemoret-nv commented on tests/llm/services/conftest.py
> +@pytest.fixture(name="mock_chat_completion", autouse=False)
Revert this change

2024-05-21 15:19 UTC, mdemoret-nv commented on tests/llm/services/test_openai_chat_client.py
> +        assert str(client._client.base_url) == arg_base_url
Will be cleaned up in #1704

2024-05-21 22:52 UTC, merged