Completely remove all use cases of MultiMessage
nv-morpheus/Morpheus pull request #1803
Opened 2024-07-08 19:05 UTC by yczhang-nv

## Description

Closes #1802 

## By Submitting this PR I confirm:
- I am familiar with the [Contributing Guidelines](https://github.com/nv-morpheus/Morpheus/blob/main/docs/source/developer_guide/contributing.md).
- When the PR is ready for review, new or existing tests cover these changes.
- When the PR is ready for review, the documentation is up to date with these changes.

2024-07-26 17:59 UTC, yczhang-nv commented
/test

2024-07-26 18:01 UTC, yczhang-nv commented
/ok to test

2024-07-26 18:21 UTC, yczhang-nv commented
/ok to test

2024-07-26 21:48 UTC, yczhang-nv commented
/ok to test

2024-07-29 17:48 UTC, yczhang-nv commented
/ok to test

2024-07-29 23:48 UTC, yczhang-nv commented
/ok to test

2024-07-29 23:53 UTC, yczhang-nv commented
/ok to test

2024-08-13 21:46 UTC, yczhang-nv commented
/ok to test

2024-08-13 22:34 UTC, yczhang-nv commented
/ok to test

2024-08-13 23:58 UTC, yczhang-nv commented
/ok to test

2024-08-14 00:19 UTC, yczhang-nv commented
/ok to test

2024-08-14 22:07 UTC, yczhang-nv commented
/ok to test

2024-08-15 16:30 UTC, yczhang-nv commented
/ok to test

2024-08-19 18:00 UTC, dagardner-nv requested changes

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/_lib/src/stages/filter_detections.cpp
> +#include <memory>      // for shared_ptr, __shared_ptr_access, make_shared
Remove `__shared_ptr_access` we shouldn't be calling out implementation detail symbols.

```suggestion
#include <memory>      // for shared_ptr, make_shared
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/_lib/src/stages/serialize.cpp
> +#include <memory>     // for shared_ptr, __shared_ptr_access, make_shared
```suggestion
#include <memory>     // for shared_ptr, make_shared
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/_lib/tests/stages/test_add_classification.cpp
> +#include <memory>      // for allocator, make_shared, __shared_ptr_access, shared_ptr
```suggestion
#include <memory>      // for allocator, make_shared, shared_ptr
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/controllers/filter_detections_controller.py
> +    def filter_slice(self, msg: ControlMessage) -> typing.List[ControlMessage]:
```suggestion
    def filter_slice(self, msg: ControlMessage) -> list[ControlMessage]:
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/controllers/monitor_controller.py
> +    def progress_sink(self, msg: typing.Union[cudf.DataFrame, MessageMeta, ControlMessage, typing.List]):
```suggestion
    def progress_sink(self, msg: cudf.DataFrame | MessageMeta | ControlMessage | list):
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/stages/inference/identity_inference_stage.py
> +        return (msg.tensors().count, self._seq_length)
```suggestion
    def calc_output_dims(self, msg: ControlMessage) -> tuple[int, int]:
        return (msg.tensors().count, self._seq_length)
```

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/stages/inference/identity_inference_stage.py
> +        return (msg.tensors().count, self._seq_length)
Not really a part of this PR, but something I'm thinking about is if `msg.tensors().count` is a common pattern, calling `msg.tensors()` might require a bit more cost than we think, we might want to consider a `tensor_count` property.

2024-08-19 18:00 UTC, dagardner-nv commented on docs/source/developer_guide/guides/9_control_messages.md
>  msg_meta = MessageMeta(data)
Update the docs above to explicitly mention that in addition to the deprecation in 24.06, in 24.10 MultiMessage was removed.

2024-08-19 18:00 UTC, dagardner-nv commented on examples/abp_pcap_detection/abp_pcap_preprocessing.py
> +        memory = _messages.InferenceMemoryFIL(count=count, input__0=data, seq_ids=seq_ids)
If this is a temporary change and the various subclasses of `TensorMemory` are going to be removed in a future PR, then feel free to ignore this comment.

I'm not sure if this is an improvement here, I think in general it is bad form to import the C++ impls directly, especially in an example where we are documenting how end-users should write custom stages.

I think we should either:
1. Continue using the Python implementations of the workflow-specific subclasses of `TensorMemory`
2. Stop using them, remove them and move everything to just use `TensorMemory` directly.

2024-08-19 18:00 UTC, dagardner-nv commented on examples/log_parsing/inference.py
>              tensors={
We should just use the Python impl of `TensorMemory` if `ControlMessage` doesn't support the the Python implementation of `TensorMemory` we should just update it to support it, mimicing what we did with the `payload_from_python_meta` method.

2024-08-19 18:00 UTC, dagardner-nv commented on python/morpheus/morpheus/stages/preprocess/train_ae_stage.py
>  from morpheus.messages.multi_ae_message import MultiAEMessage
We should be removing `MultiAEMessage` as well.

2024-08-29 17:25 UTC, yczhang-nv commented
/ok to test

2024-08-29 18:46 UTC, yczhang-nv commented
/ok to test

2024-08-29 21:04 UTC, yczhang-nv commented
/ok to test

2024-09-06 19:47 UTC, dagardner-nv commented on examples/ransomware_detection/stages/create_features.py
I think `examples/ransomware_detection/stages/preprocessing.py` needs to be updated as well

2024-09-06 19:49 UTC, dagardner-nv commented on morpheus/pipeline/multi_message_stage.py
This looks like a merge error

2024-09-06 19:50 UTC, dagardner-nv commented on python/morpheus/morpheus/stages/preprocess/preprocess_ae_stage.py
>  from morpheus.stages.preprocess.preprocess_base_stage import PreprocessBaseStage
I think the `PreprocessBaseStage` needs to be updated as well

2024-09-06 20:12 UTC, yczhang-nv commented
/ok to test

2024-09-06 21:56 UTC, yczhang-nv commented
/ok to test

2024-09-06 22:01 UTC, yczhang-nv commented
/ok to test

2024-09-06 22:02 UTC, yczhang-nv commented
/ok to test

2024-09-06 22:59 UTC, yczhang-nv commented
/ok to test

2024-09-06 23:29 UTC, yczhang-nv commented
/ok to test

2024-09-09 05:59 UTC, yczhang-nv commented
/ok to test

2024-09-09 06:04 UTC, yczhang-nv commented
/ok to test

2024-09-09 22:18 UTC, yczhang-nv commented
/ok to test

2024-09-09 22:27 UTC, yczhang-nv commented
/ok to test

2024-09-09 22:49 UTC, yczhang-nv commented
/ok to test

2024-09-09 23:16 UTC, yczhang-nv commented
/ok to test

2024-09-10 00:43 UTC, yczhang-nv commented
/ok to test

2024-09-10 21:07 UTC, mdemoret-nv commented
/ok to test

2024-09-10 21:14 UTC, mdemoret-nv commented
/ok to test

2024-09-10 22:42 UTC, yczhang-nv commented
/merge

2024-09-10 22:53 UTC, dagardner-nv approved these changes
Looks good, just one small docstring fix needed

2024-09-10 22:53 UTC, dagardner-nv commented on python/morpheus/morpheus/_lib/include/morpheus/stages/add_scores_stage_base.hpp
> +/**************AddScoresStageBase***************************/
Good catch!

2024-09-10 22:53 UTC, dagardner-nv commented on python/morpheus/morpheus/utils/concat_df.py
> +    messages : list[ControlMessage] | list[cudf.DataFrame]
The type hint in the function def should match the hint in the docstring.

2024-09-10 23:34 UTC, mdemoret-nv approved these changes

2024-09-10 23:37 UTC, yczhang-nv commented
/ok to test

2024-09-11 00:04 UTC, yczhang-nv commented
/ok to test

2024-09-11 16:07 UTC, yczhang-nv commented
/merge

2024-09-11 16:07 UTC, merged