Support for automated AE feature selection (DFP)
nv-morpheus/Morpheus pull request #1816
Opened 2024-07-19 13:17 UTC by dnandakumar-nv

Closes part of : https://github.com/nv-morpheus/Morpheus/issues/1685: "[FEA]: Automated Feature Selection in DFP and building DataFrame schemas from JSON definition files"

This pull request adds two a utility class to the autoencoder folder to decrease time-to-value in workflows. 

`AutoencoderFeatureSelector`: Given a dataset, this runs a few rudimentary statistical tests and studies on the dataset to recommend which features might be most helpful when training a DFP Autoencoder. This class also builds JSON schema definitions that can be used in the `JSONSchemaBuilder`.

This pull request also provides accompanying demo notebooks that demonstrate the usage and limitations of the provided utility class.

2024-07-24 19:48 UTC, mdemoret-nv requested changes

2024-07-24 19:48 UTC, mdemoret-nv commented on morpheus/models/dfencoder/ae_feature_selector.py
> +        select_features(k_min, k_max): Selects features based on importance, adhering to min/max constraints.
This docstring is in the wrong format. Convert it to follow the [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) specification

2024-07-24 19:48 UTC, mdemoret-nv commented on morpheus/models/dfencoder/ae_feature_selector.py
> +        self.final_features = self.df.columns.tolist()  # Initialize with all features
Are all of these properties which can be changed by the user of the class? If any of these should not be changed, convert them to private variables with a leading `_`

2024-07-24 19:48 UTC, mdemoret-nv commented on morpheus/models/dfencoder/ae_feature_selector.py
> +    def train_autoencoder(self, dataframe):
Add type annotations for `dataframe`

2024-07-24 19:48 UTC, mdemoret-nv commented on morpheus/models/dfencoder/ae_feature_selector.py
> +    def calculate_loss(self, model: AutoEncoder, data: pd.DataFrame):
Does this only support pandas dataframes?

2024-07-24 19:48 UTC, mdemoret-nv commented on tests/dfencoder/test_ae_feature_selector.py
> +    assert isinstance(mask, np.ndarray)
Is there anything else we can verify about the returned data besides the shape? Can we compare to a given known good result? For example, do we know which data points are "low variance" that we can verify they have been removed?

2024-07-26 13:40 UTC, dnandakumar-nv commented on morpheus/models/dfencoder/ae_feature_selector.py
> +    def train_autoencoder(self, dataframe):
Fixed.

2024-09-06 19:26 UTC, mdemoret-nv commented
/ok to test

2024-10-31 16:24 UTC, dagardner-nv commented
re-targeting to branch-25.02

2025-03-14 22:12 UTC, closed without merging