Mdd debug conda build
nv-morpheus/Morpheus pull request #242
Opened 2022-06-29 16:49 UTC by mdemoret-nv

Fixes #240 

Looks like conda-build doesnt download LFS files regardless of what you do: https://github.com/conda/conda-build/issues/1462. They have had a PR to fix this for a while it looks like: https://github.com/conda/conda-build/pull/4318.

This PR just removes the files in `morpheus/data/**` from LFS. These files are small, downloaded automatically, and included inside of the conda package so they shouldnt be LFS.

2022-06-29 19:53 UTC, dagardner-nv requested changes

2022-06-30 04:38 UTC, dagardner-nv approved these changes

2022-06-30 04:46 UTC, mdemoret-nv commented on ci/scripts/jenkins/test.sh
> +${MORPHEUS_ROOT}/scripts/fetch_data.py check
Removed

2022-06-30 05:30 UTC, mdemoret-nv commented
@gpucibot merge

2022-06-30 05:31 UTC, merged