Draft: Simplify Python impl for KafkaSourceStage
nv-morpheus/Morpheus pull request #300
Opened 2022-07-22 15:32 UTC by dagardner-nv

Current impl is overly complicated making use of undocumented methods.

2022-10-21 23:51 UTC, dagardner-nv commented
/rerun tests

2022-10-24 16:18 UTC, mdemoret-nv requested changes
Are there any tests that compare the C++ and Python implementations?

2022-10-24 20:07 UTC, dagardner-nv commented
> Are there any tests that compare the C++ and Python implementations?

I just added one, its a bit tricky as commits perform asynchronously. I had to add a new bool constructor argument to enable blocking commits. 

Even then the C++ impl commits just after calling `on_next`

2022-11-07 19:52 UTC, mdemoret-nv approved these changes
Looks good. Lets get `branch-22.11` merged so we can get CI passing again.

2022-11-07 19:52 UTC, mdemoret-nv commented on morpheus/stages/input/kafka_source_stage.py
> +        # TODO : Needs to batch records until _stop_requested, _PARTITION_EOF or batch size has been hit
Is this `TODO` still needed?

2022-11-14 22:05 UTC, dagardner-nv commented on morpheus/stages/input/kafka_source_stage.py
> +        # TODO : Needs to batch records until _stop_requested, _PARTITION_EOF or batch size has been hit
Good catch

2022-11-15 20:38 UTC, mdemoret-nv commented
@gpucibot merge

2022-11-15 20:38 UTC, merged