Add documentation to LinearBoundary stages
nv-morpheus/Morpheus pull request #418
Opened 2022-10-26 19:09 UTC by drobison00

Resolves #413

2022-11-02 15:58 UTC, mdemoret-nv requested changes
Looks good. I think we need to add a docstring to `LinearPipeline.add_segment_boundary()` as well since thats the interface most users will use to interact with the segments at first.

2022-11-02 15:58 UTC, mdemoret-nv commented on morpheus/stages/boundary/linear_boundary_stage.py
> +        boundary_ingress = LinearBoundaryIngressStage(config, "my_boundary_port", int)
Same here. Remove this example in favor of one on `LinearPipeline.add_segment_boundary()`

2022-11-03 21:04 UTC, drobison00 commented on morpheus/stages/boundary/linear_boundary_stage.py
> +        boundary_egress = LinearBoundaryEgressStage(config, "my_boundary_port", int)
I'll leave the basic usage example here, and add your suggestion to the LinearPipeline .

2022-11-03 21:34 UTC, drobison00 commented
@mdemoret-nv Updated based on your most recent comments.

2022-11-03 23:54 UTC, mdemoret-nv approved these changes
Just one fix then it looks good.

2022-11-03 23:54 UTC, mdemoret-nv commented on morpheus/pipeline/linear_pipeline.py
> +            pipe.run()
```suggestion
            # Create a config and pipeline
            config = Config()
            pipe = LinearPipeline(config)

            # Add a source in Segment #1
            pipe.set_source(FileSourceStage(config, filename=val_file_name, iterative=False))

            # Add a segment boundary
            # [Current Segment] - [Egress Boundary] ---- [Ingress Boundary] - [Next Segment]
            pipe.add_segment_boundary(MessageMeta)

            # Add a sink in Segment #2
            pipe.add_stage(WriteToFileStage(config, filename=out_file, overwrite=False))

            pipe.run()
```
Remove unnecessary `\n`

2022-11-08 16:57 UTC, mdemoret-nv commented
@gpucibot merge

2022-11-08 16:57 UTC, merged