Clarifications and improvements to Kafka manual testing documentation
nv-morpheus/Morpheus pull request #422
Opened 2022-10-27 21:11 UTC by dagardner-nv

* Address feedback from #290 
* Add note about automated Kafka tests, which didn't exist at time the document was first written
* Fix spelling errors

Fixes #322

2022-11-08 22:53 UTC, pdmack requested changes
@dagardner-nv @mdemoret-nv I wonder if the testing instructions should just stop at the basic copy, partition tests instead of the pipelines which are covered elsewhere. There's been a fair amount of divergence (e,g., HAMMAH->DFP) and I guess I'm worried that this will be a bit of a maintenance headache.

2022-11-08 22:53 UTC, pdmack commented on scripts/validation/kafka_testing.md
>  1. Verify the output with, expect to see `43` un-matched rows:
Only got 19.
```
Results do not match. Diff 991/1010 (98.118812 %). First 10 mismatched rows:
Empty DataFrame
Columns: [data, pred]
Index: []```

2022-11-08 23:15 UTC, dagardner-nv commented
> I wonder if the testing instructions should just stop at the basic copy, partition tests instead of the pipelines which are covered elsewhere.

I think there is some truth to this, when I wrote the document I wanted to mimic each of the four pipelines in the `scripts/validation` directory. However the Kakfa version of those four pipelines have been codified into tests that are now run as a part of CI.

2022-11-08 23:18 UTC, dagardner-nv commented on scripts/validation/kafka_testing.md
> +```
I think so, this appears to be errors when kafka & zookeeper are being shut down.

2022-11-09 20:34 UTC, dagardner-nv commented on scripts/validation/kafka_testing.md
> +mamba install -c conda-forge "openjdk=11.0.15"
> @dagardner-nv should this be changed to the apt install?

The advantage for the conda/mamba install is that it doesn't require root permissions.

2022-11-14 17:40 UTC, pdmack commented
@gpucibot merge

2022-11-14 17:40 UTC, merged