Fix ambiguous segfault for test requiring MORPHEUS_ROOT
nv-morpheus/Morpheus pull request #514
Opened 2022-12-02 18:26 UTC by cwharris

Fixes #401

2022-12-03 06:44 UTC, cwharris commented
rerun tests

2022-12-07 18:50 UTC, mdemoret-nv requested changes

2022-12-07 18:50 UTC, mdemoret-nv commented on morpheus/_lib/tests/CMakeLists.txt
> +  test_morpheus.cpp
Keep these sorted.

2022-12-07 18:50 UTC, mdemoret-nv commented on morpheus/_lib/tests/test_morpheus.hpp
> +std::filesystem::path get_morpheus_root();
Add a doxygen string here describing the method

2022-12-07 19:27 UTC, mdemoret-nv approved these changes
Can merge once CI is passing

2022-12-08 07:02 UTC, cwharris commented
@gpucibot merge

2022-12-08 07:02 UTC, merged