Update to PyTorch 1.12
nv-morpheus/Morpheus pull request #523
Opened 2022-12-07 21:52 UTC by efajardo-nv

Update to PyTorch 1.12. Fixes errors seen in training scripts/notebooks when using large batch sizes.

Close #491

2022-12-12 17:06 UTC, efajardo-nv commented
rerun tests

2022-12-12 17:07 UTC, efajardo-nv commented
/rerun tests

2022-12-14 22:56 UTC, mdemoret-nv requested changes
Couple of changes needed.

2022-12-14 22:56 UTC, mdemoret-nv commented on docker/conda/environments/requirements.txt
> +git+https://github.com/nv-morpheus/dfencoder.git@branch-22.11#egg=dfencoder
Should probably be 23.01 now

2022-12-14 22:56 UTC, mdemoret-nv commented on models/validation-inference-scripts/phishing-models/phish-bert-inference-script.py
> +
You should put a comment before and after these imports indicating why they need to go first and to prevent isort from rearranging them.

2022-12-14 22:56 UTC, mdemoret-nv commented on models/validation-inference-scripts/root-cause-models/root-cause-inference.py
> +
You should put a comment before and after these imports indicating why they need to go first and to prevent isort from rearranging them.

2022-12-14 22:56 UTC, mdemoret-nv commented on setup.py
> +        "dfencoder @ git+https://github.com/nv-morpheus/dfencoder.git@branch-22.11#egg=dfencoder",
Again, this should probably be 23.01 now

2022-12-15 18:51 UTC, mdemoret-nv commented
@gpucibot merge

2022-12-15 18:51 UTC, merged