Indicate Triton Server requirement in basic usage docs
nv-morpheus/Morpheus pull request #589
Opened 2023-01-03 22:09 UTC by cwharris

2023-01-07 02:08 UTC, mdemoret-nv approved these changes

2023-01-17 17:43 UTC, dagardner-nv commented
I think this might be a duplicate of #598 which was merged and now includes Triton launch instructions loading only the `sid-minibert` model, and I'm not sure adding an additional link helps much.

The link included is broken as it goes up two directory levels instead of just one (probably my fault as I've been moving stuff around).

2023-01-17 18:12 UTC, dagardner-nv requested changes

2023-01-17 18:12 UTC, dagardner-nv commented on docs/source/basics/building_a_pipeline.md
> +This example shows an NLP Pipeline which uses several stages available in Morpheus. This example utilizes the Triton Inference Server to perform inference, and writes the output to a Kafka topic name
```suggestion
This example shows an NLP Pipeline which uses several stages available in Morpheus. This example utilizes the Triton Inference Server to perform inference, and writes the output to a Kafka topic named `inference_output`. Both of which need to be started prior to launching Morpheus. Follow [these](../getting_started.md#launching-triton-server) steps for more information on launching a Triton server.
```

2023-01-17 18:21 UTC, cwharris commented
Closing per David's suggestion.

2023-01-17 18:21 UTC, closed without merging